server:
  port: 8686

# https://viblo.asia/p/spring-logback-config-E375zg6bKGW
#logging:
#  level:
#    root: info
#  file:
#    path: logs
#    name: ${logging.file.path}/elk.log
#  pattern:
#    file: "%d{dd-MM-yyyy HH:mm:ss.SSS} [%thread] %-5level %logger{36}.%M - %msg%n"
#    console: "%d{dd-MM-yyyy HH:mm:ss.SSS} %magenta([%thread]) %highlight(%-5level) %logger.%M - %msg%n"