server:
  port: 8488

spring:
  redis:
    host: localhost
    port: 6379
  cache:
    type: redis
    redis:
      time-to-live: 300s
      key-prefix: myapp-cache
      use-key-prefix: true
      cache-null-values: true