version: '3'

# https://medium.com/@disa2aka/docker-deployments-for-keycloak-and-postgresql-e75707b155e5
# https://github.com/eabykov/keycloak-compose/blob/main/compose.yml
# only run using terminal works, using Intellij button here does not work.
services:
  postgres:
    image: postgres:${POSTGRES_VERSION}
    restart: unless-stopped
    container_name: postgres
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "keycloak"]
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:${KC_VERSION}
    command: ["start-dev"]
    restart: unless-stopped
    container_name: keycloak
    environment:
      KC_DB: postgres
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KC_DB_URL: "jdbc:postgresql://postgres:5432/keycloak"
      KC_LOG_LEVEL: ${KC_LOG_LEVEL}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    ports:
      - ${KC_PORT}:8080